- hosts: ec2
  tasks:
    - name: install pip3
      apt: name=python3-pip state=present 
      
    - name: Install Docker  Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Pull code from github
      ansible.builtin.git:
        repo: "git@github.com:christmknd/Age-Calculator-React"
        dest: ~/age-calculator
        version: "main"
        clone: true
        update: true

    - name: Pull and run new image
      become: true
      community.docker.docker_compose:
        project_src: ~/age-calculator
        state: present
        pull: true
        