- hosts: ec2
  gather_facts: false
  become: true
  become_user: root

  tasks:
    - name: install pip3
      yum: name=python3-pip state=present 

    - name: Pull code from github
      ansible.builtin.git:
        repo: https://github.com/christmknd/Age-Calculator-React.git
        dest: ec2-user/Age-Calculator-React
        version: main
        clone: true
        update: true

    - name : Go to the right folder
      become: true
      shell : cd Age-Calculator-React