- name: Deploy App
  hosts: ec2
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Docker
      become: true
      yum:
        name: docker
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Pull Docker image
      become: true
      docker_image:
        name: christmknd/age-calculator
        source: pull

    - name: Run Docker container
      become: true
      docker_container:
        name: age-calculator
        image: christmknd/age-calculator
        ports:
          - 3000:3000
        state: started
