name : Main CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3     
      with:
        node-version: 18

    - name: Build docker image 
      run: docker build -t christmknd/age-christmknd/age-calculator

    - name: Push Docker Image to  Docker Hub
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker build -t christmknd/age-christmknd/age-calculator .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push christmknd/age-christmknd/age-calculator
