name : Main CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3     
      with:
        node-version: 18

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with: 
        context: ./app         
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/age-calculator

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook : playbook.yml
        directory: ./ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: inv.ini
